language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: stable
    - rust: beta
  fast_finish: true
script:
  - cargo install cargo-xbuild
  - cargo install bootimage --version "^0.7.7"
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cargo xtest
