[package]
name = "mngr"
version = "0.1.0"
authors = ["Bruno Flores <bruno@brunoflores.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.8.1"
